import {slideImage} from './deck-visuals.js';
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const [, ,mid,pid]=location.pathname.split('/');
try{
 const response=await fetch(`/api/matches/${mid}/decks/${pid}`);if(!response.ok)throw Error('Submission unavailable. Open this URL in the browser that owns the game.');
 const data=await response.json();data.project ||= {...data.dapp,architecture:data.dapp?.blockchain};$('#title').textContent=data.project.name;const intro=document.createElement('p');intro.textContent=`Proposed interface: ${data.project.interface} Planned functions: ${data.project.functions.join('; ')}. This shared workspace demo illustrates basic interactions; project-specific AI functions remain a specification.`;$('#demo').prepend(intro);$('#status').textContent=`Frozen submission · Round ${data.round}`;
 const images=data.deck.map((_,i)=>slideImage(data,i));let current=0;
 $('#slides').innerHTML=`<div class="slide-controls"><button id="previous-slide" aria-label="Previous slide">←</button><span id="slide-position" role="status"></span><button id="next-slide" aria-label="Next slide">→</button><button id="download-slide">Save slide image ↓</button><button id="print-deck">Print / save PDF</button></div><div class="slide-stage">${data.deck.map((s,i)=>`<article class="visual-slide" data-slide="${i}" ${i?'hidden':''}><img src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(images[i])}" alt="${esc(s.title)} — visual slide"><details class="slide-notes"><summary>Speaker notes & source details</summary><p>${esc(s.body)}</p></details></article>`).join('')}</div><div class="slide-thumbnails" aria-label="Choose slide">${data.deck.map((s,i)=>`<button data-slide-go="${i}" aria-label="Slide ${i+1}: ${esc(s.title)}"><img src="data:image/svg+xml;charset=utf-8,${encodeURIComponent(images[i])}" alt=""><span>${i+1}</span></button>`).join('')}</div>`;
 const go=index=>{current=Math.max(0,Math.min(images.length-1,index));document.querySelectorAll('[data-slide]').forEach((e,i)=>e.hidden=i!==current);document.querySelectorAll('[data-slide-go]').forEach((e,i)=>e.setAttribute('aria-current',i===current?'true':'false'));$('#slide-position').textContent=`${current+1} / ${images.length}`;$('#previous-slide').disabled=current===0;$('#next-slide').disabled=current===images.length-1};
 $('#previous-slide').onclick=()=>go(current-1);$('#next-slide').onclick=()=>go(current+1);document.querySelectorAll('[data-slide-go]').forEach(b=>b.onclick=()=>go(+b.dataset.slideGo));
 document.addEventListener('keydown',e=>{if($('#slides').hidden||e.target.closest('input,textarea,select,button,summary'))return;if(e.key==='ArrowRight'){e.preventDefault();go(current+1)}if(e.key==='ArrowLeft'){e.preventDefault();go(current-1)}});
 $('#download-slide').onclick=()=>{const url=URL.createObjectURL(new Blob([images[current]],{type:'image/svg+xml'}));const a=document.createElement('a');a.href=url;a.download=`${mid}-${pid}-slide-${current+1}.svg`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
 $('#print-deck').onclick=()=>window.print();go(0);
 $('#show-deck').onclick=()=>{$('#slides').hidden=false;$('#demo').hidden=true};$('#show-demo').onclick=()=>{$('#slides').hidden=true;$('#demo').hidden=false};
 let proposals=[];const key=`project-demo-${mid}-${pid}`;try{proposals=JSON.parse(localStorage.getItem(key)||'[]')}catch{}
 const log=text=>{const li=document.createElement('li');li.textContent=text;$('#activity').prepend(li)};
 const draw=()=>{$('#proposals').innerHTML=proposals.map((p,i)=>`<article class="artifact"><strong>${esc(p.text)}</strong><p>${p.votes} feedback · ${p.done?'Completed':'Open'}</p><meter min="0" max="${Math.max(10,p.votes)}" value="${p.votes}"></meter><button data-vote="${i}">Mark useful</button><button data-done="${i}" ${p.done?'disabled':''}>Record completion</button></article>`).join('');localStorage.setItem(key,JSON.stringify(proposals));document.querySelectorAll('[data-vote]').forEach(b=>b.onclick=()=>{proposals[+b.dataset.vote].votes++;log('Feedback recorded locally.');draw()});document.querySelectorAll('[data-done]').forEach(b=>b.onclick=()=>{proposals[+b.dataset.done].done=true;log('Completion recorded locally.');draw()})};
 $('#create').onclick=()=>{const text=$('#proposal').value.trim();if(!text)return;proposals.push({text,votes:0,done:false});$('#proposal').value='';log('Item created locally.');draw()};draw();
}catch(e){$('#status').textContent=e.message}
